# .streamlit/config.toml

[general]
# Optional: Set your app's name here
# headless = true
# enableCORS = false
# enableXsrfProtection = false

[server]
headless = true
enableCORS = false
port = $PORT
enableXsrfProtection = false
fileWatcherType = "poll"

[runtime]
pythonVersion = "3.10"
